### ISSUE TITLE
err404 npm install --save @ionic-native/star-prnt

### ISSUE THREAD

**Issue by soesantos** [infoxicator/StarprnDemoIonicV2#1]
hi jose,
i cant install and save ionic-native/star-prnt from npm, have you removed it?

npm ERR! code E404
npm ERR! 404 Not Found: @ionic-native/star-prnt@latest

**Comment by infoxicator** [comment]
Hi @soesantos, I can see that the plugin is on the 4.7.0 version of Ionic Native but it is not pulling it from npm. In the meantime, try adding the plugin manually I will check with the ionic team 

Ruben

**Comment by soesantos** [comment]
hi Ruben, thanks you so much for your reply,
i am beginner in ionic iam using ionic v.3.20.0
could you pls to advise how to add plugin manually

**Comment by infoxicator** [comment]
Hi @soesantos the Ionic Team said that the plugin won't be available through npm until there is a new version release, maybe in 1 or 2 weeks time. You can install it manually by downloading a copy of the star-prnt folder [here](https://github.com/infoxicator/StarprnDemoIonicV2/tree/master/star-prnt) and placing it in your app's node_modules/@ionic-native/ folder

**Comment by infoxicator** [comment]
Hi @soesantos I believe the ionic team has added the ionic-native plugin to npm now
